name: Despertador del Museo
on:
  schedule:
    - cron: '0 0,12 * * *' # Se ejecuta automáticamente cada 12 horas
  workflow_dispatch: # Permite que tú lo actives a mano si quieres

jobs:
  wake_up:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Actualizar latido
        run: |
          echo "Último despertar: $(date)" > heartbeat.txt
          
      - name: Guardar cambios
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add heartbeat.txt
          git commit -m "App despierta"
          git push
