name: Wake Up App
on:
  schedule:
    - cron: '*/30 * * * * 
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: curl -I https://calendario2026-museodelhambre.streamlit.app
